Mob test build
Team-SmilingCat/Project-Mars pull request #22
Opened 2022-03-03 08:19 UTC by stevenleej

Added enemy model and animations

Added enemy 1's behaviour tree and animator

switched player movement to switch statements for certain conditions to ease readability

2022-03-03 19:15 UTC, Vassenx requested changes

2022-03-03 19:15 UTC, Vassenx commented on The_Dune_Project/Assets/Scripts/Fight/EnemyController.cs
> +    protected void LoadAgentProperties(EnemyController e)
you dont need the parameter EnemyController e

2022-03-03 19:15 UTC, Vassenx commented on The_Dune_Project/Assets/Scripts/Fight/MeleeEnemyController.cs
> +        base.Update();
unnecessary func

2022-03-03 19:15 UTC, Vassenx commented on The_Dune_Project/Assets/Scripts/Fight/MeleeEnemyController.cs
> +    public void ReturnToOriginalLocation()
when is this called?

2022-03-03 19:15 UTC, Vassenx commented on The_Dune_Project/Assets/Scripts/Fight/MeleeEnemyController.cs
> +        if (distance <= lookRadius)
can just do
return distance <= lookRadius
although its less readable
nitpick ^

2022-03-04 19:29 UTC, stevenleej commented on The_Dune_Project/Assets/Scripts/Player/PlayerMovement.cs
> +        if(!playerHookHandler.finishedHook){
interacting skips the player movement loop; for example, when a player's animation parameter is set to isInteracting, relevant code which comes after does not run (in our case, moving and turning)

2022-03-04 19:53 UTC, stevenleej commented on The_Dune_Project/Assets/Scripts/Fight/MeleeEnemyController.cs
> +        base.Update();
you need to call it or unity won't update the cooldowns on the mob (monobehaviour and inheritance with update functions is stupid)

2022-03-04 19:54 UTC, stevenleej commented on The_Dune_Project/Assets/Scripts/Fight/MeleeEnemyController.cs
> +    public void ReturnToOriginalLocation()
to go back to the original location in the behaviour tree (assuming it's the return to original location function)

2022-03-06 22:30 UTC, merged